Automated update: seg 14 abr 2025 12:09:27 WEST

diff --git a/docker/Dockerfile.build.ubuntu22.cross-arm64 b/docker/Dockerfile.build.ubuntu22.cross-arm64
--- a/docker/Dockerfile.build.ubuntu22.cross-arm64
+++ b/docker/Dockerfile.build.ubuntu22.cross-arm64
@@ -25,7 +25,7 @@
 #
 #---------------------------------------------------------------------
 
-FROM ran-base:latest AS ran-build
+FROM ran-base:local AS ran-build
 
 RUN rm -Rf /oai-ran
 WORKDIR /oai-ran
@@ -33,24 +33,24 @@ COPY . .
 
 # build all targets so final targets can be created afterwards
 RUN /bin/sh oaienv && \
-    cd cmake_targets && \
-    mkdir -p log ran_build/build ran_build/build-cross && \
-    cd ran_build/build && \
-    cmake ../../.. -GNinja && \
-    echo "====== Start of log for host-tools ======" && \
-    ninja ldpc_generators generate_T > ../../log/host-tools.txt 2>&1 && \
-    echo "====== End of log for host-tools ======" && \
-    cd ../build-cross/ && \
-    # install missing libyaml-cpp-dev for arm64
-    apt install -y libyaml-cpp-dev:arm64 && \
-    cmake ../../.. -GNinja -DENABLE_TELNETSRV=ON \
-      -DCMAKE_TOOLCHAIN_FILE=../../../cmake_targets/cross-arm.cmake -DNATIVE_DIR=../build \
-      -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" && \
-    echo "====== Start of log for cross-build executables ======" && \
-    # making always passing so we can analyze the all.txt file
-    ninja -k10 dlsim ulsim ldpctest polartest smallblocktest nr_pbchsim nr_dlschsim nr_ulschsim nr_dlsim nr_ulsim nr_pucchsim nr_prachsim lte-softmodem nr-softmodem nr-cuup oairu lte-uesoftmodem nr-uesoftmodem params_libconfig coding rfsimulator telnetsrv > ../../log/all.txt 2>&1; \
-    # displaying errors and warnings
-    grep -E -A3 "warning:|error:" ../../log/all.txt || true && \
-    # will fail only if string "errors:" is found
-    grep -E "error:" -vqz ../../log/all.txt && \
-    echo "====== End of log for cross-build executables ======"
+  cd cmake_targets && \
+  mkdir -p log ran_build/build ran_build/build-cross && \
+  cd ran_build/build && \
+  cmake ../../.. -GNinja && \
+  echo "====== Start of log for host-tools ======" && \
+  ninja ldpc_generators generate_T > ../../log/host-tools.txt 2>&1 && \
+  echo "====== End of log for host-tools ======" && \
+  cd ../build-cross/ && \
+  # install missing libyaml-cpp-dev for arm64
+  apt install -y libyaml-cpp-dev:arm64 && \
+  cmake ../../.. -GNinja \
+  -DCMAKE_TOOLCHAIN_FILE=../../../cmake_targets/cross-arm.cmake -DNATIVE_DIR=../build \
+  -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror" && \
+  echo "====== Start of log for cross-build executables ======" && \
+  # making always passing so we can analyze the all.txt file
+  ninja -k10 nr-uesoftmodem params_libconfig coding rfsimulator dfts params_yaml > ../../log/all.txt 2>&1; \
+  # displaying errors and warnings
+  grep -E -A3 "warning:|error:" ../../log/all.txt || true && \
+  # will fail only if string "errors:" is found
+  grep -E "error:" -vqz ../../log/all.txt && \
+  echo "====== End of log for cross-build executables ======"
